const stai2024 = [
    { question: "1. Las fórmulas Erlang, respecto al dimensionamiento de sistemas de información se utilizan para:", answers: ["El dimensionamiento de telecomunicaciones.", "El dimensionamiento de servidores.", "Consolidar infraestructuras.", "La automatización de procesos."], correct: 0 },
    
  //  { question: "2. ¿Cuándo aplican las referencias del Real Decreto 1125/2024 de 5 de noviembre a la Agencia Estatal de Administración Digital?", answers: ["Desde su entrada en vigor, el 8 de noviembre de 2024.", "En la próxima legislatura.", "Cuando se produzca su constitución efectiva.", "Pasados 6 meses desde la publicación del Real Decreto."], correct: 2 },
    
 //   { question: "3. Los conjuntos de datos de alto valor son:", answers: ["Datos derivados de investigaciones financiadas públicamente que son plenamente reutilizables, interoperables y de acceso abierto.", "Datos derivados de documentos sobre los que existan prohibiciones o limitaciones en el derecho de acceso.", "Datos para cuyo acceso se requiera ser titular de un derecho o interés legítimo.", "Datos a los que la Comisión Europea otorgue dicho carácter, así que como aquellos previstos a nivel nacional que sean seleccionados en relación a su potencial para generar beneficios socioeconómicos o medioambienteales importantes y servicios innovadores o beneficiar a un gran número de usuarios o pymes, entre otros aspectos."], correct: 3 },
    
 //   { question: "4. De acuerdo con el artículo 13 del Real Decreto 1125/2024, ¿a quién corresponde establecer los criterios técnicos y de oportunidad para la contratación centralizada de materia TIC?", answers: ["A la Agencia Estatal de Administración Digital.", "A la Dirección General de Digitalización.", "A la Secretaría de Estado de Digitalización.", "A la Subsecretaría del Ministerio para la Transformación Digital y de la Función Pública."], correct: 0 },
    
    { question: "5. El análisis de sensibilidad que evalúa cómo cambian los resultados cuando se alteran las variables clave, es uno de los pasos previstos en el:", answers: ["Análisis coste/beneficio.", "Ciclo PDCA o Ciclo de Deming.", "Análisis GAP.", "Diagrama causa-efecto o de Ishikawa."], correct: 0 },
    
    { question: "6. Indique cuál de las siguientes afirmaciones sobre el Sistema de Valor de Servicios (SVS) de ITIL 4 es correcta:", answers: ["El SVS de ITIL está compuesto únicamente por las cuatro dimensiones del modelo de gestión del servicio.", "El propósito del SVS es garantizar que los componentes y actividades de la organización trabajen de forma coordinada para facilitar la creación de valor.", "El SVS de ITIL 4 excluye las prácticas de gestión de servicios, ya que se centran en procesos específicos.", "La mejora continua no es una parte del SVS de ITIL 4."], correct: 1 },
    
    { question: "7. El grado, cantidad o volumen de riesgo que podrá resistir una organización, se denomina:", answers: ["Propensión al riesgo.", "Análisis del riesgo.", "Tolerancia al riesgo.", "Umbral de riesgo."], correct: 2 },
    
    { question: "8. En un diagrama PERT:", answers: ["Una prelación de convergencia indica que para iniciar una actividad ha de finalizar una única actividad.", "Una prelación lineal indica que para iniciar dos actividades se han de terminar dos o más actividades.", "Las prelaciones son las condiciones que indican en que orden deben ejecutarse las actividades.", "Una prelación de divergencia indica que para iniciar dos o más actividades no hace falta terminar ninguna actividad."], correct: 2 },
    
    { question: "9. ¿Cuál de las siguientes técnicas se utilizaría para priorizar requisitos en el marco de trabajo Scrum?", answers: ["Técnica MoSCoW.", "Técnica SWOT.", "Técnica PERT.", "Técnica Gantt."], correct: 0 },
    
    { question: "10. Según la guía CCN-STIC-802, el equipo auditor deberá estar dirigido y tutelado siempre por un Auditor Jefe, responsable de gestionar las actividades de auditoría, que deberá probar como mínimo:", answers: ["Acreditación de formación y experiencia en auditoría de sistemas de información, a través de certificaciones reconocidas a nivel nacional e internacional, o bien a través de experiencia verificable y evidenciada de al menos 4 años, en auditoría de tecnologías de la información.", "Acreditación de formación y experiencia en auditoría de sistemas de información, a través de certificaciones reconocidas a nivel nacional e internacional, o bien a través de experiencia verificable y evidenciada de al menos 5 años, en auditoría de tecnologías de la información.", "Acreditación de formación y experiencia en auditoría de sistemas de información, a través de certificaciones reconocidas a nivel exclusivamente nacional, o bien a través de experiencia verificable y evidenciada de al menos 5 años, en auditoría de tecnologías de la información.", "Acreditación de formación y experiencia en auditoría de sistemas de información, a través de certificaciones reconocidas a nivel exclusivamente nacional, o bien a través de experiencia verificable y evidenciada de al menos 4 años, en auditoría de tecnologías de la información."], correct: 1 },
    
    { question: "11. ¿Cuál de las siguientes afirmaciones es correcta respecto de la adquisición por parte de las entidades públicas del derecho de uso de activos de software en la nube?", answers: ["Es un contrato mixto, puesto que las prestaciones del contrato son las de adquisición de licencia de uso de los activos de software y la de servicios en la nube.", "Es un contrato de servicios, puesto que las prestaciones del contrato son las de servicios en la nube.", "Es un contrato de suministros, a menos que se trate del desarrollo de programas de ordenador a medida del órgano de contratación en la nube, que será un contrato de servicios.", "Es un contrato de servicios, a menos que se trate del desarrollo de programas de ordenador a medida del órgano de contratación en la nube, que será un contrato de suministros."], correct: 0 },
    
    { question: "12. ¿En qué actividad del Estudio de Viabilidad del Sistema en Métrica V3 se utiliza la técnica de análisis coste beneficio?", answers: ["Estudio de alternativas de solución.", "Selección de la solución.", "Valoración de las alternativas.", "Recolección de los requisitos del sistema."], correct: 2 },
    
    { question: "13. ¿Qué se entiende por demanda latente en los recursos de un sistema?", answers: ["Cantidad de trabajo útil ejecutado por unidad de tiempo en un entorno de carga determinado.", "Máxima cantidad de trabajo útil por unidad de tiempo en un entorno de carga determinada.", "En el estudio de la capacidad de los sistemas de información, es el trabajo frenado por la falta de recursos.", "Media entre los valores del MTBF (tiempo medio entre fallos) y del MTTR (tiempo medio de reparaciones)."], correct: 2 },
    
    { question: "14. ¿Cuál es el propósito principal de calcular el VAN de un proyecto?", answers: ["Determinar el costo total del proyecto.", "Evaluar la rentabilidad de la inversión.", "Calcular los ingresos futuros.", "Estimar los costos operativos."], correct: 1 },
    
    { question: "15. ¿Qué debe incluir, como mínimo, la declaración de accesibilidad que cada entidad del sector público debe publicar en su sitio web para cumplir con la Decisión de Ejecución (UE) 2018/1523 de la Comisión, de 11 de octubre de 2018?", answers: ["Informe detallado de los errores de accesibilidad según la WCAG, preparación de la declaración, observaciones y datos de contacto y procedimiento de aplicación.", "Situación de cumplimiento, contenido no accesible, preparación de la declaración, observaciones y datos de contacto y procedimiento de aplicación.", "Situación de cumplimiento, contenido no accesible, enlace a informe de evaluación, preparación de la declaración y observaciones y datos de contacto.", "Situación de cumplimiento, contenido no accesible, preparación de la declaración, y observaciones y datos de contacto."], correct: 1 },
    
    { question: "16. El Esquema Nacional de Interoperabilidad, según el artículo 156 de la Ley 40/2015, de 1 de octubre, comprende:", answers: ["Las obligaciones a que están sujetas las Administraciones Públicas para garantizar una correcta interoperabilidad de sus sistemas, redes y aplicaciones en su relación con la ciudadanía.", "Los criterios técnicos que han de seguir las Administraciones Públicas en el desarrollo, contratación y puesta a disposición de herramientas tecnológicas por los departamentos ministeriales.", "El conjunto de criterios y recomendaciones en materia de seguridad, conservación y normalización de la información, de los formatos y de las aplicaciones que deberán ser tenidos en cuenta por las Administraciones Públicas para la toma de decisiones tecnológicas que garanticen la interoperabilidad.", "La política de seguridad en la utilización de medios electrónicos por las Administraciones Públicas."], correct: 2 },
    
    { question: "17. ¿Cuál es el objeto de la NTI del Catálogo de Estándares en el Esquema Nacional de Interoperabilidad?", answers: ["Establecer un conjunto completo de estándares utilizados por las administraciones públicas.", "Establecer una lista de restricciones sobre las aplicaciones y herramientas que cada administración utiliza para su gestión interna.", "Establecer un conjunto mínimo de estándares basados en criterios definidos para garantizar la interoperabilidad.", "Establecer un procedimiento de homologación de estándares para el intercambio de información entre administraciones y ciudadanos."], correct: 2 },
    
    { question: "18. Según la metodología MAGERIT, ¿cuál es el primer paso en el proceso de análisis de riesgos?", answers: ["Identificación de amenazas.", "Determinación del impacto residual.", "Identificación de activos.", "Aplicación de salvaguardas."], correct: 2 },
    
    { question: "19. En el marco del Real Decreto 311/2022, de 3 de mayo, por el que se regula el Esquema Nacional de Seguridad (ENS), los sistemas de información serán objeto de un proceso para determinar su conformidad. Asimismo, las entidades de certificación responsables deben estar acreditadas, conforme a la norma \"Evaluación de la conformidad. Requisitos para organismos que certifican productos, procesos y servicios\". ¿Qué norma es ésta?", answers: ["UNE-EN ISO/IEC 17065:2012.", "UNE-EN ISO/IEC 17026:2015.", "UNE-EN ISO/IEC 17021:2015.", "UNE-EN ISO/IEC 17011:2017."], correct: 0 },
    
    { question: "20. Las normas o recomendaciones publicadas por ITU-T se agrupan en series según su temática. ¿Cuál de las siguientes NO es una serie ITU-T?", answers: ["B. Servicios de Benchmarking (por ejemplo, B.25 codificación de pruebas).", "G. Sistemas y medios de transmisión, sistemas y redes digitales (por ejemplo, G.711 codificación de audio PCM).", "I. Red Digital de Servicios integrados, RDSI (por ejemplo, I.120: Redes digitales de servicios integrados).", "H. Sistemas audiovisuales y multimedia (por ejemplo, H.323 sistemas de comunicaciones multimedia basados en paquetes)."], correct: 0 },
    
    { question: "21. ¿Cuáles de los siguientes son planes de España Digital 2026?", answers: ["Plan Nacional de Ciberseguridad, Plan Nacional de Competencias Digitales.", "Plan de Servicios Públicos Digitales, Plan de Confianza en el Ámbito Digital.", "Plan de TIC en PYME, Programa de Fomento del Uso de la Factura Electrónica.", "Plan de Internacionalización de Empresas Tecnológicas, Plan de Impulso de la Economía Digital y los Contenidos Digitales."], correct: 0 },
    
    { question: "22. En el contexto de la System Availability Infrastructure (SAI-Infraestructura de Disponibilidad del Sistema), ¿cuál de las siguientes afirmaciones describe correctamente cómo la SAI contribuye a la resiliencia en un sistema distribuido?", answers: ["La SAI almacena copias de seguridad de todos los datos en cada nodo, lo que permite una recuperación rápida y evita la pérdida de información en caso de fallo.", "La SAI utiliza un sistema de escalabilidad dinámica, redistribuyendo automáticamente las tareas a medida que aumentan los requisitos de procesamiento para evitar la sobrecarga de nodos específicos.", "La SAI monitorea de forma continua el estado de los nodos y redistribuye automáticamente las tareas de los nodos con fallos hacia nodos operativos, minimizando la interrupción de los servicios.", "La SAI garantiza que todos los nodos estén sincronizados en tiempo real, asegurando la coherencia de datos entre nodos y la disponibilidad de servicios."], correct: 2 },
    
    { question: "23. ¿Cómo se denomina al sistema híbrido centralizado que engloba la gestión de información de seguridad y la gestión de eventos, proporcionando un análisis en tiempo real de las alertas de seguridad generadas por los distintos dispositivos hardware y software de la red?", answers: ["COCS.", "SIEM.", "NAC.", "IDS."], correct: 1 },
    
    { question: "24. ¿Cuál es la principal función de las soluciones EMM (Enterprise Mobility Management) en dispositivos móviles?", answers: ["Administrar el acceso a redes inalámbricas.", "Proporcionar aplicaciones de productividad.", "Gestionar la seguridad y políticas corporativas en dispositivos.", "Monitorizar el uso de aplicaciones de entretenimiento."], correct: 2 },
    
    { question: "25. ¿Cuál de las siguientes es una tecnologías de orquestación cloud-edge de código abierto desarrollada en la Unión Europea?", answers: ["Open Eucalyptus.", "Open Nebula.", "Open Ware.", "Open Stack."], correct: 1 },
    
    { question: "26. En el ámbito de las políticas de backup (respaldo), señale la respuesta correcta:", answers: ["La copia de seguridad incremental realiza copia de los archivos y directorios que han sido modificados desde la última copia completa.", "La copia de seguridad incremental es igual que la copia de seguridad diferencial, pero sin borrar el bit de modificado.", "La copia de seguridad incremental ahorra tiempo pero ocupa el mismo espacio en cinta con respecto a la copia de seguridad completa.", "La copia de seguridad incremental realiza copia de los archivos y directorios que han sido modificados desde la última copia, ya sea completa o no."], correct: 3 },
    
    { question: "27. ¿Qué afirmación es correcta respecto a los distintos tipos de clúster?", answers: ["De alta disponibilidad: disponen de nodos redundantes, de manera que se siga proporcionando servicio aunque alguno de los componentes del clúster falle.", "De alta confiabilidad o balanceo de carga: la carga de trabajo se distribuye sólo entre parte de los servidores, el resto se dedica a asegurar disponibilidad.", "De alto rendimiento: dividen las tareas de procesamiento entre una parte de los nodos componentes del clúster, mediante procesamiento secuencial.", "De alta seguridad: la carga de trabajo se reparte entre varios servidores para asegurar que todos llegan al mismo resultado."], correct: 0 },
    
    { question: "28. ¿Cúal de los siguientes sistemas es un servicio común que se basa en una arquitectura orientada a servicios (SOA)?", answers: ["Servicio de Verificación y Consulta de Datos: Plataforma de Intermediación.", "REÚNETE: Servicio Común de Reuniones Virtuales de la Red SARA.", "SICRES: Sistema de Información Común de Registros de Entrada y Salida.", "CoFFEE-MRR: Sistema de información que soporta la gestión del Plan de Recuperación, Transformación y Resiliencia."], correct: 0 },
    
    { question: "29. ¿Cuál es el propósito de la memoria virtual en un sistema operativo?", answers: ["Limitar el uso de la CPU por cada proceso.", "Permitir que el sistema operativo ejecute programas más grandes que la memoria física disponible.", "Controlar el acceso de los usuarios a los recursos del sistema.", "Mejorar la velocidad de procesamiento en la RAM."], correct: 1 },
    
    { question: "30. Desde el punto de vista de los recursos lógicos, indique cuál de los siguientes es un estado almacenable para ficheros abiertos por un proceso en UNIX:", answers: ["El proceso está sleeping y el swapper lo ha transferido al almacenamiento primario para hacer sitio en la memoria virtual.", "El proceso ha finalizado y se encuentra en estado de registro, existe pero no se halla preparado para funcionar de nuevo ni está durmiendo.", "El proceso está en ejecución y se halla preparado para funcionar en modo kernel, a la espera de que el swapper lo decida.", "El proceso está volviendo desde el kernel al modo usuario, pero el kernel le da preeminencia a este último y hace un cambio de contexto para realizar otro proceso."], correct: 0 },
    
    { question: "31. El sistema operativo Darwin, base de macOS:", answers: ["Utiliza un núcleo desarrollado íntegramente por Apple.", "Es un software de código abierto.", "Incluye la interfaz Aqua como parte de su distribución.", "Es una versión del sistema operativo linux."], correct: 1 },
    
    { question: "32. En relacion con los lenguajes del SGBD, el lenguaje que se utiliza para especificar el esquema de la base de datos (creación, modificación y borrado de tablas), las vistas de los usuarios y las estructuras de almacenamiento es el:", answers: ["Lenguaje de manipulación de datos (LMD o DML, de Data Manipulation Language).", "Lenguaje de control de datos (LCD o DCL, de Data Control Language).", "Lenguajes de control de transacciones: (LCT o TCL Transaction Cotrol Language).", "Lenguaje de definición de datos (LDD o DDL, de Data Definition Language)."], correct: 3 },
    
    { question: "33. El cálculo relacional de tuplas es un lenguaje de consulta:", answers: ["Imperativo.", "Declarativo.", "De procesamiento paralelo.", "Procedimental."], correct: 1 },
    
    { question: "34. ¿Qué tipo de cifrado utiliza HTTPS para asegurar la comunicación entre el cliente y el servidor?", answers: ["Cifrado asimétrico en la negociación, seguido de cifrado simétrico en la transmisión de datos.", "Cifrado simétrico únicamente, usando una clave precompartida.", "Cifrado por flujo, utilizando una clave de sesión única para cada mensaje.", "Cifrado de capa de transporte sin autenticación del servidor."], correct: 0 },
    
    { question: "35. ¿Qué componente de .NET es responsable de ejecutar aplicaciones?", answers: ["Visual Studio.", "Common Language Runtime (CLR).", "Entity Framework.", "Microsoft SQL Server."], correct: 1 },
    
    { question: "36. ¿Cómo ayuda el patrón MVC a mejorar la eficiencia en el desarrollo y mantenimiento de aplicaciones cuando se manejan múltiples plataformas (por ejemplo, una versión web y una versión móvil)?", answers: ["Permite que tanto la vista como el modelo se compartan entre plataformas, lo que reduce el tiempo de desarrollo y las pruebas necesarias para cada plataforma.", "Al centralizar todas las funciones de la vista en un único componente, MVC asegura que el diseño sea uniforme en todas las plataformas, eliminando la necesidad de optimizar para diferentes tamaños de pantalla.", "La separación entre la vista y el modelo permite que se puedan crear vistas específicas para cada plataforma sin afectar la lógica de negocio, mejorando la eficiencia en el desarrollo y mantenimiento.", "No es adecuado para aplicaciones que deben soportar múltiples plataformas, ya que requiere una reescritura completa de las vistas para cada plataforma."], correct: 2 },
    
    { question: "37. ¿Cuál es una característica de PHP?", answers: ["Es un lenguaje compilado.", "Solo funciona en servidores Windows.", "Es un lenguaje de código abierto y multiplataforma.", "No soporta bases de datos."], correct: 2 },
    
    { question: "38. ¿Cuál de los siguientes aspectos contempla el artículo 16, del Real Decreto 4/2010, sobre las condiciones de licenciamiento de las aplicaciones informáticas de una Administración Pública?", answers: ["La obligación de celebrar un convenio para realizar el licenciamiento.", "La ausencia total de responsabilidad por parte del cesionario con respecto al cedente en caso de errores o mal funcionamiento de la aplicación.", "La exención de responsabilidad del cedente por un posible mal uso por parte del cesionario.", "La obligación de asistencia técnica o de mantenimiento por parte del cedente."], correct: 2 },
    
    { question: "39. ¿Cuál de las siguientes siglas corresponde a un lenguaje de comunicación y consultas del conocimiento que permite la interacción y comunicación entre agentes inteligentes?", answers: ["KQML.", "FIPA.", "DML.", "JADE."], correct: 0 },
    
    { question: "40. En el ámbito de la ciencia de datos, la ténica \"binning\":", answers: ["Permiten realizar operaciones sobre datos cifrados sin necesidad de desencriptarlos primero.", "Permite transformar datos continuos en categorías discretas.", "Permite, para cada entrada en el conjunto de entrenamiento, producir una salida conocida (o etiqueta) que el algoritmo utiliza para aprender la relación entre las características (input) y las etiquetas (output).", "Permite descubrir patrones y segmentar los datos de entrada."], correct: 1 },
    
    { question: "41. ¿Cuál de las siguientes afirmaciones describe correctamente a SAP HANA?", answers: ["Es una solución ERP de SAP diseñada para pequeñas y medianas empresas, enfocada en la gestión integral.", "Es una plataforma de base de datos en memoria para asegurar su alto rendimiento.", "Es el modelo de datos estándar empleado en los sistemas SAP para centralizar información.", "Es el lenguaje de programación principalmente utilizado en el desarrollo de aplicaciones SAP."], correct: 1 },
    
    { question: "42. ¿Qué estructura tienen las declaraciones de xAPI para registrar eventos de aprendizaje?", answers: ["usuario, evento, curso.", "actor, verbo, objeto.", "rol, acción, contexto.", "alumno, tarea, resultado."], correct: 1 },
    
    { question: "43. ¿Cuál es la finalidad principal de la Directiva INSPIRE en la Unión Europea?", answers: ["Crear una infraestructura para compartir información geográfica entre Estados miembros.", "Regular el uso de GPS para navegadores personales.", "Desarrollar estándares únicos para mapas temáticos.", "Reducir los costos de almacenamiento de datos geográficos."], correct: 0 },
    
    { question: "44. ¿Qué técnica utilizaría en un entorno de compartición de datos para garantizar el principio de minimización de datos señalado por el RGPD?", answers: ["Algoritmos de Compresión.", "Pruebas de conocimiento cero.", "Indexación de Bases de Datos.", "Filtrado Cuántico de Relevancia."], correct: 1 },
    
    { question: "45. ¿Cuál es la diferencia principal entre la gestión del dato y la gestión de la calidad del dato?", answers: ["La gestión del dato se refiere a la encriptación de los datos almacenados, mientras que la gestión de la calidad del dato se centra en asegurar la precisión, consistencia y confiabilidad de los datos.", "La gestión del dato se refiere a la creación y almacenamiento de los datos, mientras que la gestión de la calidad del dato se refiere a la seguridad y administración de los datos.", "La gestión del dato asegura la precisión, consistencia y confiabilidad de los datos, mientras que la gestión de la calidad del dato se centra en la seguridad y administración de los datos.", "La gestión del dato asegura que los datos satisfacen los requisitos de negocio, mientras que la gestión de la calidad del dato asegura que los datos son adecuados para el uso que se pretende hacer de ellos."], correct: 3 },
    
    { question: "46. ¿Cuál es el motor de renderizado del navegador web Safari?", answers: ["Webkit.", "Blink.", "Gecko.", "Trident."], correct: 0 },
    
    { question: "47. ¿Cuál de las siguientes medidas se aplicaría en una pasarela de pago que cumpla con el estándar PCI DSS?", answers: ["Almacenar los datos de las tarjetas en servidores externos y asegurarse de que estén disponibles para futuras transacciones sin necesidad de reautenticación.", "Utilizar encriptación para proteger los datos durante la transmisión, pero permitir el acceso completo a los datos al personal del comercio.", "Realizar la tokenización de los datos sensibles de las tarjetas, reemplazándolos por un identificador único no reversible.", "Requerir que todos los clientes proporcionen una contraseña para cada transacción, aunque no sea necesaria para pagos recurrentes."], correct: 2 },
    
    { question: "48. La criptografía asimétrica:", answers: ["Implica que la seguridad se deposita en una única clave, secreta o privada, que es compartida por emisor y receptor.", "Supone que si tenemos un número n de personas que necesitan comunicarse entre sí, se necesitan en total n(n-1)/2 claves para todas las parejas de personas que tengan que comunicarse de modo privado.", "Requiere que cada usuario posea un par de claves privadas, una clave que solo conoce el emisor y otra que solo conoce el receptor.", "Se fundamenta en la imposibilidad práctica de resolver ciertos problemas matemáticos de forma eficiente."], correct: 3 },
    
    { question: "49. ¿Cuál es el formato y firma que deben emplearse en la generación de facturas electrónicas de acuerdo con la Norma Técnica de Interoperabilidad (NTI) de Política de firma y sello electrónicos y de certificados de la Administración?", answers: ["EPES con firma electrónica XAdES.", "Facturae con firma electrónica PAdES.", "Facturae con firma electrónica XAdES.", "EPES con firma electrónica PAdES."], correct: 2 },
    
    { question: "50. ¿Cuál es la entidad que identifica de forma inequívoca al solicitante de un certificado y suministra a otra entidad los datos verificados de éste a fin de que se pueda emitir el correspondiente certificado?", answers: ["Autoridad de Registro (RA).", "Autoridad de Certificación (CA).", "Autoridad de Emisión (EA).", "Autoridad de Validación (VA)."], correct: 0 },
    
    { question: "51. ¿Cuál es la guía que articula el mecanismo de Declaración y Certificación de Conformidad con el Esquema Nacional de Seguridad (ENS), determinando las condiciones para alcanzar dicho cumplimiento normativo?", answers: ["Guía CCN-STIC 812.", "Guía CCN-STIC 823.", "Guía CCN-STIC 809.", "Guía CCN-STIC 803."], correct: 3 },
    
    { question: "52. Según la Norma Técnica de Interoperabilidad de Digitalización de Documentos, la digitalización de un documento deberá contener:", answers: ["El índice electrónico.", "Los metadatos mínimos obligatorios.", "La firma de la imagen electrónica.", "La firma del índice electrónico."], correct: 1 },
    
    { question: "53. El uso de sistemas biométricos para el tratamiento del registro de jornada y control de acceso con fines laborales es, según el RGPD:", answers: ["Un tratamiento prohibido, ya que supone un tratamiento de alto riesgo que incluye categorías especiales de datos.", "Un tratamiento lícito si se basa en una norma con rango de ley que autorice específicamente su uso para dicha finalidad.", "Un tratamiento lícito si el interesado dio su consentimiento para el tratamiento de sus datos personales para uno o varios fines específicos.", "Un tratamiento lícito al ser necesario para el cumplimiento de una misión realizada en interés público o en el ejercicio de poderes públicos conferidos al responsable del tratamiento."], correct: 1 },
    
    { question: "54. En el ámbito del Blockchain y de la Identidad Digital Soberana (Self-Sovereign Identity, SSI):", answers: ["Los identificadores descentralizados (DIDs) y las credenciales verificables se almacenan en blockchain.", "Los usuarios gestionan sus identificadores descentralizados (DIDs) y credenciales verificables mediante una billetera digital.", "Los identificadores descentralizados (DIDs) son emitidos exclusivamente por instituciones gubernamentales.", "Las billeteras digitales se utilizan únicamente para realizar pagos."], correct: 1 },
    
    { question: "55. ¿Cuál de las siguientes afirmaciones describe correctamente el concepto de integración continua en el desarrollo de software?", answers: ["Implementar actualizaciones al sistema en tiempo real sin pruebas previas para agilizar los despliegues.", "Realizar pruebas manuales ocasionales para validar el código desarrollado antes de integrarlo en el repositorio principal.", "Automatizar la integración de los cambios de código de varios contribuidores en un único proyecto de software.", "Esperar a que todos los módulos estén completados antes de realizar una integración para evitar conflictos de código."], correct: 2 },
    
    { question: "56. ¿Cómo se llama el metódo de evaluación utilizado por el modelo EFQM?", answers: ["REDER.", "EVAM.", "CAF.", "RED."], correct: 0 },
    
    { question: "58. ¿Qué establece la ley 39/2015, de 1 de octubre, del Procedimiento Administrativo Común de las Administraciones Públicas, respecto del archivo de documentos?", answers: ["Cada organización elaborará y mantendrá actualizados y documentados los procedimientos de gestión de documentos a seguir en los distintos procesos de gestión documental.", "El personal de las organizaciones recibirá la formación específica y adecuada a su rol necesaria para la gestión y conservación de documentos y expedientes electrónicos.", "No se podrá asegurar el traslado de los datos a otros formatos y soportes que garanticen el acceso desde diferentes aplicaciones.", "Los documentos electrónicos deberán conservarse en un formato que permita garantizar la autenticidad, integridad y conservación del documento."], correct: 3 },
    
    { question: "59. ¿Cuál de son las dimensiones de gestión de servicios de tecnologías de la información que introduce ITIL 4?", answers: ["Organizaciones; información y tecnología; socios; flujos de valor y procesos.", "Organizaciones y personas; tecnología; socios y proveedores; actividades y procedimientos.", "Organizaciones y personas; información y tecnología; socios y proveedores; flujos de valor y procesos.", "Información y tecnología; socios y proveedores; actividades y procedimientos."], correct: 2 },
    
    { question: "60. ¿En qué se basan los ordenadores cuánticos?", answers: ["En la estructura subatómica de la materia.", "En la estructura atómica de la materia.", "En la estuctura molecular de la materia.", "En las fuerzas intermoleculares de la materia."], correct: 0 },
    
    { question: "61. El modelo de proceso en espiral:", answers: ["Es un modelo en cascada evolutivo, dividido en ciclos en el que se aplican un conjunto de actividades, utilizando herramientas que ayuden a esta labor.", "Permite el desarrollo del software en versiones incrementales, y está dividido en ciclos en el que se aplican un conjunto de actividades.", "Permite la producción automática de diseño y código, a partir de una especificación formal de un producto software utilizando herramientas que ayuden a esta labor.", "Permite la reutilización de piezas de código ya existente (espiral de uso), que ensamblados mediante interfaces estándar reduce el ciclo de desarrollo."], correct: 0 },
    
    { question: "62. En Kanban, ¿qué representa una tarjeta en el tablero Kanban?", answers: ["La persona del equipo responsable y sus tareas completadas.", "El período de tiempo establecido para completar un conjunto de tareas.", "Una tarea o ítem de trabajo que necesita ser completado.", "Una reunión planificada y aún pendiente para revisar el progreso del equipo."], correct: 2 },
    
    { question: "63. En un modelo entidad-relación, ¿cómo se implementa una relación de cardinalidad \"muchos a muchos\" entre dos entidades en el diseño de bases de datos?", answers: ["Mediante una relación directa entre las dos entidades.", "Mediante una clave foránea en una de las entidades.", "Mediante una tabla intermedia, que contiene las claves primarias de las dos entidades.", "Incluyendo un atributo X adicional en cada una de las entidades, siendo un atributo de la otra entidad."], correct: 2 },
    
    { question: "64. Los símbolos de diagramas BPMN se clasifican en los siguientes grupos principales:", answers: ["Objetos de flujo, objetos de datos, objetos de conexión y almacenes.", "Objetos de flujo, objetos de datos, carriles y artefactos.", "Objetos de flujo, objetos de conexión, carriles y almacenes.", "Objetos de flujo, objetos de conexión, carriles y artefactos."], correct: 3 },
    
    { question: "65. ¿Qué requisitos no funcionales define el cumplimiento con normativas legales?", answers: ["Requisitos de rendimiento.", "Requisitos organizativos.", "Requisitos de producto.", "Requisitos externos."], correct: 3 },
    
    { question: "66. En el modelo de vista arquitectónica 4+1, la quinta vista es un pequeño conjunto de casos de uso o escenarios utilizados para ilustrar la descripción de la arquitectura, ¿cuáles son las otras cuatro?", answers: ["La vista de proceso, la vista de desarrollo, la vista de despliegue y la vista física.", "La vista lógica, la vista de desarrollo, la vista de proceso y la vista física.", "La vista lógica, la vista de desarrollo, la vista de proceso y la vista funcional.", "La vista lógica, la vista de desarrollo, la vista de implementación y la vista de despliegue."], correct: 1 },
    
    { question: "67. ¿Cuál de las siguientes respuestas describe el patrón de diseño \"Singleton\"?", answers: ["Permite que una clase tenga solo una instancia y proporciona un punto de acceso global a esa instancia.", "Define una familia de algoritmos, encapsula cada uno y los hace intercambiables.", "Separa la construcción de un objeto complejo de su representación para que el mismo proceso de construcción pueda crear diferentes representaciones.", "Proporciona una interfaz para crear familias de objetos relacionados o dependientes sin especificar sus clases concretas."], correct: 0 },
    
    { question: "68. En MÉTRICA V3, en relación a las interfaces, las descritas en la metodología son:", answers: ["La Gestión de Proyectos, la Mejora de Procesos, la Gestión del Personal y la Gestión de la Configuración del Producto.", "La Gestión de Proyectos, la Seguridad, el Aseguramiento de la Calidad y la Gestión de la Configuración.", "La Gestión de Proyectos, la Seguridad, la Mejora de Procesos y la Gestión de la Configuración.", "La Gestión de Proyectos, la Mejora de Procesos, el Aseguramiento de la Calidad y la Gestión de la Configuración."], correct: 3 },
    
    { question: "69. Las pruebas de caja negra sirven para:", answers: ["Verificar que los requisitos funcionales de la aplicación se cumplen mediante casos de prueba deducidos de la estructura interna del programa.", "Verificar que los requisitos funcionales de la aplicación se cumplen, siendo la estructura interna del programa irrelevante.", "Poder verificar partes del código mediante casos de prueba deducidos de la estructura interna del programa.", "Poder verificar extractos del código, contando con acceso al código."], correct: 1 },
    
    { question: "70. ¿Cuál de las siguientes opciones describe correctamente el término \"Pipeline\" en el contexto de Integración Continua (CI)?", answers: ["Una serie de pruebas manuales que deben ejecutarse antes de cada despliegue.", "Un conjunto de etapas automatizadas que procesan el código, desde la construcción hasta el despliegue.", "Un repositorio de código que debe ser actualizado antes de cada despliegue.", "Un paso dentro del proceso de integración continua que se ejecuta una sola vez al final del ciclo de vida de la aplicación."], correct: 1 },
    
    { question: "71. ¿Cómo se denomina el grado de relación que existe entre los datos y métodos o funciones internos de un módulo?", answers: ["Acoplamiento.", "Cohesión.", "Complejidad.", "Código duplicado."], correct: 1 },
    
    { question: "72. ¿Cuál de los siguientes es un método de medición de Puntos de Función de un proyecto software?", answers: ["Técnicas Delphi.", "COCOMO.", "COSMIC FFP.", "SPFP."], correct: 2 },
    
    { question: "73. En el desarrollo de un proyecto de software, LOC es:", answers: ["Una métrica basada en tokens.", "Una medida de la longitud del código fuente.", "Una medida de diagramas de flujo de datos.", "Una medida de especificaciones algebraicas."], correct: 1 },
    
    { question: "74. ¿Qué establece la Ley de Shannon-Hartley?", answers: ["Que, para un determinado modo de transmisión asignado, existe una capacidad máxima que vendrá dada por la relación eficiencia/ruido.", "Que, para una determinada razón de muestreo, existe una capacidad máxima que vendrá dada por la relación señal/ruido.", "Que, para un determinado ancho de banda asignado, existe una capacidad máxima que vendrá dada por la relación señal/ruido.", "Que, para un determinado ancho de banda asignado, existe una señal aparente máxima que vendrá dada por la relación capacidad/ruido."], correct: 2 },
    
    { question: "75. ¿Qué dominio de alto nivel (TLD) de la ICANN/IANA sería elegible para organizaciones de tratados y organizaciones con estatus de observadoras de la ONU?", answers: [".ARPA", ".INT", ".ORG", ".UNO"], correct: 1 },
    
    { question: "76. Indique la norma europea en la que se regula la compatibilidad electromagnética de los equipos:", answers: ["Directiva 2014/30/UE, del Parlamento Europeo y del Consejo, de 26 de febrero de 2014.", "Reglamento 2014/30/UE, del Parlamento Europeo y del Consejo, de 26 de febrero de 2014.", "Decisión 2014/30/UE, del Parlamento Europeo y del Consejo, de 26 de febrero de 2014.", "Recomendación 2014/30/UE, del Parlamento Europeo y del Consejo, de 26 de febrero de 2014."], correct: 0 },
    
    { question: "77. En un sistema basado en el modelo OSI, una aplicación solicita el establecimiento de una conexión con un servidor remoto. ¿Cuál es el orden correcto de primitivas que podrían utilizarse en este proceso?", answers: ["REQUEST, INDICATION, RESPONSE, CONFIRM.", "INDICATION, REQUEST, CONFIRM, RESPONSE.", "REQUEST, RESPONSE, INDICATION, CONFIRM.", "RESPONSE, REQUEST, INDICATION, CONFIRM."], correct: 0 },
    
    { question: "78. ¿Qué características definen las \"mmWave\", dentro del espectro de ondas de radio empleadas para transmisión de datos, por ejemplo, para las redes 5G?", answers: ["Se corresponden con la banda 10, SHF, gama de frecuencias (excluido el límite inferior, pero incluido el superior) de 3 a 30GHz y subdivisión métrica 10mm-1mm.", "Se corresponden con la banda 11, EHF, gama de frecuencias (excluido el límite inferior, pero incluido el superior) de 30 a 300GHz y subdivisión métrica 10mm-1mm.", "Se corresponden con la banda 10, EHF, gama de frecuencias (excluido el límite inferior, pero incluido el superior) de 30 a 300GHz y subdivisión métrica 1mm-0,1mm.", "Se corresponden con la banda 11, SHF, gama de frecuencias (excluido el límite inferior, pero incluido el superior) de 3 a 30GHz y subdivisión métrica 1mm-0,1mm."], correct: 1 },
    
    { question: "79. ¿Cuál es el estándar de encapsulamiento en el que se define el mecanismo para realizar túneles Ethernet Q-in-Q (también conocido como \"VLAN stacking\")?", answers: ["IEEE 802.1Q.", "IEEE 802.1p.", "IEEE 802.3ad.", "IEEE 802.1ad."], correct: 3 },
    
    { question: "80. De acuerdo con la Ley 11/2022, de 28 de junio, General de Telecomunicaciones, indique cuál de las opciones enunciadas a continuación caracteriza el espectro radioeléctrico:", answers: ["Es un bien de dominio público, cuya titularidad y administración están compartidas entre el Estado y las Comunidades Autónomas.", "Es un bien de dominio público, cuya titularidad y administración corresponden al Estado.", "Es un bien de dominio público, cuya titularidad corresponde al Estado y la administración a las Comunidades Autónomas.", "Es un bien de dominio público, cuya titularidad y administración está transferida a las Comunidades Autónomas."], correct: 1 },
    
    { question: "81. ¿Cuál de las siguientes afirmaciones sobre la estructura de una dirección IPv6 es correcta?", answers: ["Una dirección IPv6 tiene un tamaño fijo de 64 bits.", "Las direcciones IPv6 se representan en notación decimal.", "Las direcciones IPv6 no pueden contener ceros a la izquierda en sus grupos.", "Una dirección IPv6 se compone de ocho grupos de cuatro dígitos hexadecimales."], correct: 3 },
    
    { question: "82. Señale la especificación que describe un método para la traducción de direcciones de red (NAT, por sus siglas en inglés):", answers: ["RFC 3202.", "RFC 2033.", "RFC 3022.", "RFC 3023."], correct: 2 },
    
    { question: "83. ¿Cómo se denomina el componente que proporciona la conexión entre redes H.323 y otras redes como PSTN o SIP?", answers: ["Gatekeeper.", "MEGAGO (Media Gateway Control).", "Gateway.", "MCU (Multipoint Control Unit)."], correct: 2 },
    
    { question: "84. ¿Cuál es la principal función de un MIB (Management Information Base) en el contexto de la gestión de redes?", answers: ["Almacenar y organizar los parámetros de configuración de los dispositivos de red, permitiendo la gestión remota a través de SNMP.", "Facilitar la recopilación y organización de datos operativos de dispositivos para su análisis en tiempo real.", "Permitir la gestión remota de dispositivos a través de la configuración de sus interfaces de red y parámetros operativos.", "Proveer información de red en formato estructurado para el control de tráfico y la gestión de recursos."], correct: 0 },
    
    { question: "85. En seguridad informática, las siglas \"AAA\" que representan el conjunto de procesos utilizados para gestionar el acceso, control y seguimiento de usuarios en una red o sistema ¿a qué términos hace referencia?", answers: ["Authentication, Access, Allocation.", "Authentication, Authorization, Accounting.", "Access, Allocation, Accountability.", "Authentication, Authorization, Audit."], correct: 1 },
    
    { question: "86. ¿Cuál de los siguientes es un servidor de aplicaciones que cumple con los estándares J2EE?", answers: ["Oracle WebLogic.", "Internet Information Server.", "Enterprise Java Beans.", "LTSP Server."], correct: 0 },
    
    { question: "87. ¿Cuál de los siguientes requisitos se contempla en la legislación vigente para poder adquirir la condición de PdP (punto de presencia) de la Red SARA?", answers: ["Que dé servicio al menos a 30 administraciones públicas, preferiblemente Entidades Locales.", "Que realice al menos 20.000 transacciones al mes para las citadas Administraciones.", "Que al conjunto de Administraciones a las que preste servicio representen al menos a una población de 400.000 habitantes.", "Que la empresa preste servicios de administración electrónica en la nube a Administraciones Públicas ubicadas en al menos a tres quintos de las Comunidades Autónomas."], correct: 2 },
    
    { question: "88. ¿Qué describe correctamente el término FTTx (fibra hasta la X)?", answers: ["Es una tecnología inalámbrica que permite conectar dispositivos directamente al núcleo de una red de fibra óptica.", "FTTx se refiere a varias arquitecturas de red donde la fibra óptica se extiende hacia el usuario final, ofreciendo alta velocidad y baja latencia.", "Es un estándar que obliga a todas las conexiones a usar exclusivamente fibra óptica sin transición a otros medios de transmisión.", "FTTx es una solución diseñada únicamente para grandes empresas, ya que no es adecuada para entornos residenciales."], correct: 1 },
    
    { question: "89. En la estructura de mensaje de correo SMTP, ¿cuál de las siguientes opciones refiere a la sección que contiene toda la información necesaria para transportar el mensaje?", answers: ["Encabezado.", "Sobre.", "Protocolo.", "Codificación."], correct: 1 },
    
    { question: "90. ¿Cómo se denomina el programa de ayudas para la provisión del conjunto de equipamiento activo e infraestructura auxiliar necesaria para la provisión de servicios de comunicaciones móviles con tecnología 5G en zonas donde no existe cobertura móvil 4G con servicio minimo de 50 Mbps?", answers: ["UNICO 5G I+D.", "UNICO 5G Redes - Pasivas.", "UNICO 5G Redes - Activas.", "UNICO 5G - Backhaul Fibra Óptica."], correct: 2 },
    
    { question: "91. ¿Qué NO debe ser declarado en el archivo de manifiesto \"AndroidManifest.xml\" de un proyecto de app en Android?", answers: ["Las funciones de diccionario, que contienen una lista de atributos, claves y valores que definen diferentes aspectos de la aplicación.", "Las funciones de hardware y software que requiere la app, que determinan qué dispositivos pueden instalar la app desde Google Play.", "Los permisos que necesita la app para acceder a las partes protegidas del sistema o a otras apps.", "Los componentes de la app, que incluyen todas las actividades, los servicios, los receptores de emisión y los proveedores de contenido."], correct: 0 },
    
    { question: "92. ¿Cuál de los siguientes ataques de ingeniería social se basa en crear un escenario o historia ficticia, donde el atacante tratará que la víctima comparta información confidencial que, en circunstancias normales, no revelaría?", answers: ["Phising.", "Baiting.", "Pretexting.", "Tailgating."], correct: 2 },
    
    { question: "93. ¿Qué nombre recibe la guía de referencia diseñada por OWASP para ayudar a las organizaciones a evaluar, medir la madurez y mejorar las prácticas de seguridad en desarrollo de software?", answers: ["OWASP SAMM.", "OWASP FSTM.", "OWASP-ZAP.", "OWASP Top Ten."], correct: 0 },
    
    { question: "94. Las acciones contra el ciberespionaje, según el Objetivo I de la Estrategia Nacional de Ciberseguridad de 2019, merecen especial atención para:", answers: ["Asegurar la protección del patrimonio tecnológico de España.", "Detectar los posibles ataques a empresas españolas.", "Garantizar el uso seguro del ciberespacio.", "Garantizar la protección de la soberanía industrial española."], correct: 0 },
    
    { question: "95. ¿Cual de las siguientes afirmaciones es correcta en relación con un plan de continuidad de negocio?", answers: ["El RTO debe ser siempre menor o igual al MTD para evitar interrupciones críticas.", "El MTD se define por el personal técnico responsable del sistema.", "El RTO siempre debe superar al RPO para garantizar una recuperación efectiva.", "El ROL se refiere al tiempo necesario para recuperar un proceso clave del negocio."], correct: 0 },
    
    { question: "96. Según establece el artículo 14.3 de la Ley 11/2022, de 28 de junio, General de Telecomunicaciones:", answers: ["Los operadores podrán negociar entre sí sin restricción acuerdos de acceso e interconexión.", "La Secretario de Estado de Telecomunicaciones e Infraestructuras Digitales podrá establecer restricciones a los precios que se establezcan en los acuerdos de acceso e interconexión.", "Los operadores deberán recabar autorización previa de la Adminstración para negociar cualquier acuerdo de acceso e interconexión.", "Los operadores podrán negociar entre sí sin restricción acuerdos de acceso e interconexión si no afecta a servicios básicos de telecomunicaciones."], correct: 0 },
    
    { question: "97. UML 2.5.1 modela el comportamiento a través de los diagramas siguientes:", answers: ["Máquinas de Estados, Interacción, Casos de Uso y Actividad.", "Máquinas de Estados, Interacción, Clases y Actividad.", "Máquinas de Estados, Secuencia, Casos de Uso y Actividad.", "Máquinas de Estados, Secuencia, Comunicación, Casos de Uso y Actividad."], correct: 0 },
    
    { question: "98. Según la guía CCN-STIC 836 Seguridad en Redes Privadas Virtuales (VPN), la VPN de acceso remoto:", answers: ["Se implementa con un servidor VPN en cada extremo de la comunicación.", "Precisa que los equipos cliente deben tener instalado y correctamente configurado el software VPN y deben autenticarse antes de poder usarla.", "Se emplea para establecer conexiones seguras entre dos equipos, protegiendo el tráfico desde un extremo al otro.", "Se emplea para proteger las comunicaciones entre dos redes, a través de una red pública, manteniendo la seguridad y enrutando las comunicaciones."], correct: 1 },
    
    { question: "99. ¿Cuál de las siguientes afirmaciones sobre las unidades NAS (Network Attached Storage) es correcta?", answers: ["Una unidad NAS solo puede ser accedida por dispositivos conectados físicamente a ella mediante USB.", "Las unidades NAS están diseñadas para el almacenamiento local y no pueden conectarse a internet.", "Una unidad NAS permite compartir y acceder a datos a través de una red, ofreciendo características como copias de seguridad y acceso remoto.", "Las unidades NAS no ofrecen opciones de redundancia de datos, ya que solo tienen un disco duro."], correct: 2 },
    
    { question: "100. Según la Guía de Comunicación Digital para la Administración General del Estado, es obligatorio que aparezcan los siguientes elementos en la cabecera de la página de inicio de un sitio web de la Administración General del Estado:", answers: ["Imagen institucional, multilingüismo, aviso legal, mapa web y buscador.", "Imagen institucional, multilingüismo, contacto, mapa web y buscador.", "Imagen institucional, contacto, mapa web, declaración de accesibilidad, buscador.", "Imagen institucional, guía de navegación, aviso Legal, mapa web y buscador."], correct: 0 },
    
    { question: "101. ¿Qué tipo de sistema de coordenadas se utiliza oficialmente en Europa y España para la referenciación geográfica?", answers: ["WGS84.", "ETRS89.", "UTM.", "NAD83."], correct: 1 },
    
    { question: "102. El Data Lake Sanitario es una actuación de la Agenda España Digital 2026, que se engloba dentro del eje:", answers: ["Eje 8. Transformación digital sectorial y sostenible.", "Eje 4. Economía del Dato e Inteligencia Artificial.", "Eje 10. Derechos digitales.", "Eje 5. Transformación digital del Sector Público."], correct: 0 },
    
    { question: "103. ¿Cuáles son los principios del marco de gobierno del modelo de referencia COBIT 2019?", answers: ["Proveer valor a los interesados, y enfoque holístico de los componentes.", "Basado en un modelo conceptual, abierto y flexible, y alineado con los estándares más relevantes.", "Sistema de gobierno dinámico, y gobierno distinto de la gestión.", "Adaptarse a las necesidades de la empresa, y sistema de gobierno \"end-to-end\"."], correct: 2 },
    
    { question: "104. En el contexto de los casos de uso y UML 2.5.1:", answers: ["La relación Extend se utiliza cuando hay algún comportamiento adicional que debe añadirse al comportamiento definido en dos o más casos de uso.", "La relación Include está pensada para ser utilizada cuando hay partes comunes del comportamiento de dos o más casos de uso.", "La relación Include se utiliza cuando hay algún comportamiento obligatorio que debe añadirse al comportamiento definido en uno o más casos de uso.", "La relación Extend se utiliza cuando hay algún comportamiento común pero adicional en dos o más casos de uso y dicho comportamiento debe especificarse dentro del comportamiento de un sólo caso de uso."], correct: 1 },
    
    { question: "105. ¿Cuál es el estándar recomendado para videoconferencia en redes IP según la ITU-T?", answers: ["H.263.", "SIP.", "H.320.", "H.323."], correct: 3 }
];
