const tema48 = [
    
    { question: "01. La firma electrónica en formato XAdES-C:", answers: ["Añade referencias a datos de verificación (certificados y listas de revocación) a los documentos firmados para permitir verificación y validación off-line.", "Añade un campo de sellado de tiempo a través de SignatureTimeStamp o de un proveedor de tiempo de confianza.", "Añade información sobre políticas de firma mediante la propiedad SignaturePolicyldentifier.", "Define la forma básica de una firma electrónica. Tiene que contener el elemento SigningCertificate o ds:Keylnfo."], correct: 0 },
    
    { question: "02. En un sistema de clave asimétrica, ¿cuál es la clave que se usa para que A (emisor) firme digitalmente un mensaje que envía al destinatario B?", answers: ["La clave pública de A.", "El certificado digital.", "La clave privada de A.", "La clave privada de B."], correct: 2 },
    
    { question: "03. ¿Cuál de los siguientes no es un modo de operación del algoritmo de cifrado DES (Data Encryption Standard)?", answers: ["ECB (Electronic Code Block Mode)", "CFB (Cypher Feedback Mode)", "BBM (Bit Block Mode)", "CBC (Cypher Block Chaining Mode)"], correct: 2 },
    
    { question: "04. Merced a este servicio, la entidad emisora obtiene una prueba, demostrable ante terceros, de la fecha y hora en que el mensaje fue enviado. ¿A qué servicio nos referimos?", answers: ["No Repudio de Envío.", "No Repudio de Conocimiento.", "No Repudio de Depósito.", "No Repudio de Transporte."], correct: 2 },
    
    { question: "05. Señale entre las siguientes qué característica NO lo es del DNIe 3.0", answers: ["La información en el chip está distribuida en tres zonas: pública, privada y de seguridad.", "Los certificados de autenticación y firma están en la zona pública.", "Incorpora tecnología NFC.", "Se puede utilizar en los Pasos Rápidos de Fronteras (ABC systems) al igual que el pasaporte electrónico."], correct: 0 },
    
    { question: "06. En una firma digital", answers: ["Se cifra con la clave privada del origen y se descifra con la clave pública del origen.", "Se cifra con la clave pública del destinatario y se descifra con la clave privada del destinatario.", "Se cifra con la clave pública del destinatario y se descifra con la clave privada del origen.", "Se cifra con la clave privada del origen y se descifra con la clave pública del destinatario."], correct: 0 },
    
    { question: "07. Usted se presenta ante una sede electrónica de una Administración para realizar un trámite y el sitio al entrar le muestra un mensaje tipo \"su certificado no es válido\". ¿Cuál puede ser la causa?", answers: ["Su certificado ha sido expedido por una autoridad de certificación que no figura entre las reconocidas por la sede electrónica.", "Partiendo de la base de que le han proporcionado su certificado en su lugar de trabajo, el certificado expedido no está basado en una autoridad de certificación de las comúnmente reconocidas, su organización, pero sin validez alguna fuera de la misma como un certificado interno del departamento, solamente válido dentro de sino que ha sido generado.", "Su certificado ha caducado.", "Todas las respuestas anteriores son posibles."], correct: 3 },
    
    { question: "08. Una clave pública permite:", answers: ["Obtener un fichero hash de un documento informático.", "Nada, puesto que es pública.", "Acceder a Internet mediante una wifi administrativa.", "Autentificar la identidad de un ciudadano."], correct: 3 },
    
    { question: "09. ¿Cuantos certificados tiene un DNIe?", answers: ["3", "2", "Variable: Depende de cuantas veces nos haya caducado", "1"], correct: 1 },
    
    { question: "10. La integridad de un documento electrónico se consigue mediante:", answers: ["El uso de un generador de resumen", "El uso del cifrado asimétrico", "El uso de una clave privada y otra pública", "El uso de un generador de claves"], correct: 0 },
    
    { question: "11. Para llevar a cabo el proceso de obtención del certificado de usuario de la FNMT, es imprescindible:", answers: ["Utilizar el mismo ordenador, sistema operativo, usuario y navegador durante todo el proceso.", "Utilizar el mismo ordenador y navegador.", "Acreditarse en la AEAT antes de comenzar el proceso de solicitud.", "Ninguna de las anteriores es correcta."], correct: 0 },
    
    { question: "12. En una firma electrónica:", answers: ["Utilizo la clave pública del destinatario para firmar y el destinatario verifica con su clave privada.", "Utilizo mi clave privada para firmar y el destinatario verifica con mi clave pública.", "Utilizo mi clave privada para firmar y el destinatario verifica con su clave privada.", "Utilizo mi clave pública para firmar y el destinatario verifica con su clave privada."], correct: 1 },
    
    { question: "13. En el DNI electrónico:", answers: ["La autoridad de certificación es la Dirección General de Policía.", "La autoridad de certificación no es la misma que la autoridad de validación.", "Hay autoridades de registro.", "Todas las anteriores son correctas."], correct: 3 },
    
    { question: "14. Para recibir un mensaje cifrado:", answers: ["El remitente cifra con mi clave pública y yo descifro con mi clave privada.", "El remitente cifra con su clave privada y yo descifro con mi clave privada.", "El remitente cifra con su clave pública y yo descifro con mi clave privada.", "El remitente cifra con su clave pública y yo descifro con su clave privada."], correct: 0 },
    
    { question: "15. La firma electrónica tendrá respecto de los datos consignados en forma electrónica el mismo valor que la firma manuscrita en relación con los consignados en papel:", answers: ["Si es avanzada y se ha generado mediante un dispositivo seguro de creación de firma.", "Si es reconocida.", "Si es avanzada.", "Si es avanzada y está basada en un certificado reconocido."], correct: 1 },
    
    { question: "16. Indique cual de las siguientes afirmaciones es cierta:", answers: ["El chip criptográfico que se encuentra en el DNI electrónico contiene, entre otros elementos, la imagen digitalizada de la firma manuscrita.", "El chip criptográfico que se encuentra en el DNI electrónico contiene, un único certificado electrónico cuyo cometido es autenticar la personalidad del ciudadano y firmar electrónicamente.", "El acceso a la funcionalidad del DNI electrónico se realiza mediante clave personal de acceso (PIN) que se encuentra a buen recaudo en la Autoridad de Certificación.", "El DNI electrónico no permite realizar una identificación biométrica del titular del mismo."], correct: 0 },
    
    { question: "17. El estándar X.509 para infraestructuras de clave pública:", answers: ["Incluye la definición de los campos obligatorios y opcionales de un certificado.", "Es un estándar definido por la Internacional Telecommunication Union.", "Define la lista de revocación de certificados (CRL)", "Todas las opciones son correctas."], correct: 3 },
    
    { question: "18. Firmar un mensaje electrónico:", answers: ["Es lo mismo que cifrarlo.", "Es lo mismo que codificarlo.", "Garantiza la confidencialidad.", "Garantiza la integridad, la autenticación y no repudio."], correct: 3 },
    
    { question: "19. Las técnicas orientadas a garantizar la seguridad en la operaciones relacionadas con los servicios de certificación y firma electrónica, deben cumplir los principios de:", answers: ["Confidencialidad, Seguridad, Integridad y Autenticación.", "Confidencialidad, Integridad, Autenticación y No Repudio.", "Disponibilidad, Integridad, Autenticación y No Repudio.", "Disponibilidad, Seguridad, Integridad y Autenticación."], correct: 1 },
    
    { question: "20. Alicia quiere enviar un mensaje confidencial a Pedro, en un sistema de clave pública, por lo tanto existen las claves Alicia-privada/Alicia-pública y Pedro-privada/Pedro-pública. Alicia genera su mensaje, ¿con qué clave de las cuatro lo cifrará?", answers: ["Alicia-privada", "Alicia-pública", "Pedro-privada", "Pedro-pública"], correct: 3 },
    
    { question: "21. Los componentes de la \"firma electrónica reconocida\" garantizan:", answers: ["La confidencialidad, integridad y el repudio.", "La confidencialidad y secreto de la información y el no repudio por parte del destinatario.", "La integridad y autenticidad de la información, y el no repudio.", "El secreto y autenticación de la información enviada."], correct: 2 },
    
    { question: "22. ¿En cuál de las siguientes respuestas aparecen todos los tipos de firma electrónica a los que hace referencia La Ley 59/2003 de firma electrónica?", answers: ["Firma manuscrita digitalizada y firma electrónica avanzada.", "Firma electrónica general o simple, firma electrónica avanzada y firma electrónica reconocida.", "Firma digital y firma manuscrita.", "Firma electrónica no vinculante, firma electrónica avanzada y firma electrónica reconocida."], correct: 1 },
    
    { question: "23. La Ley 59/2003 establece que el prestador de servicios de certificación debe:", answers: ["Almacenar los datos de creación de firma de la persona a la que haya prestado sus servicios.", "Almacenar y copiar los datos de creación de firma de la persona a la que haya prestado sus servicios.", "Constituir un seguro de responsabilidad civil por importe de al menos 1.000.000 de euros, para hacer frente a posibles negligencias.", "Garantizar la disponibilidad de un servicio de consulta sobre la vigencia de los certificados, rápido y seguro."], correct: 3 },
    
    { question: "24. En lo referente a dispositivos de firma electrónica, de acuerdo con la Ley 59/2003, señala cuál es la respuesta correcta.", answers: ["Un dispositivo de creación de firma es un programa o sistema informático que sirve para aplicar los datos de verificación de firma.", "Un dispositivo seguro de creación de firma garantiza que la firma se verifique de forma fiable.", "Los datos de verificación de firma son datos, como códigos o claves criptográficas públicas, que el firmante utiliza para crear la firma electrónica.", "Los datos de creación de firma son datos únicos, como códigos o claves criptográficas privadas, que el firmante utiliza para crear la firma electrónica."], correct: 3 },
    
    { question: "25. Tal y como indica la Ley 9/2014, General de Telecomunicaciones, en su artículo 84, tienen competencia sancionadora (señale la respuesta FALSA):", answers: ["El Secretario de Estado de Telecomunicaciones y para la Sociedad de la Información.", "La Comisión Nacional de los Mercados y la Competencia.", "El Ministro de Industria, Energía y Turismo.", "La Agencia Española de Protección de Datos."], correct: 3 },
    
    { question: "26. Según la Ley 56/2007, de Medidas de Impulso de la Sociedad de la Información, las empresas de especial trascendencia económica para la prestación de servicios al público tienen la obligación de disponer de un medio de interlocución telemática para los trámites correspondientes al ejercicio de los derechos de sus clientes sobre:", answers: ["La actualización de sus datos de cliente, que incluirán información sobre su historial de facturación de, al menos, los últimos tres años y el contrato suscrito.", "La transmisión de datos entre empresas de especial trascendencia económica.", "La tramitación completa de quejas, incidencias, sugerencias y, en su caso, reclamaciones.", "El acceso, rectificación, cancelación y oposición en los términos previstos en la normativa reguladora de protección de datos de carácter personal."], correct: 3 },
    
    { question: "27. En el campo de la criptografía….", answers: ["Los sistemas de clave privada se conocen como criptosistemas Kerckhoffs.", "Los sistemas de clave privada o simétricos son, en general, mucho más rápidos que los de clave pública o asimétricos.", "Los sistemas de clave privada o simétricos son igual de rápidos que los de clave pública o asimétricos.", "La seguridad de un sistema descansa en que el cifrado sea en bloque."], correct: 1 },
    
    { question: "28. Los sistemas de autenticación se dividen en tres grandes grupos (pudiéndose combinar entre ellos) y son los siguientes:", answers: ["Los basados en algo que conocemos (por ejemplo, una contraseña), los basados en algo poseído y los basados en sistemas biométricos.", "Los que utilizan usuario y password, los que utilizan sistemas LDAP y los que utilizan tarjetas inteligentes.", "Los basados en algo que se es, los que utilizan infraestructura PKI y los basados en contraseñas seguras.", "Los basados en tarjetas con criptoprocesador, los que utilizan sistemas biométricos y los basados en sistemas LDAP."], correct: 0 },
    
    { question: "29. En una infraestructura de clave pública (PKI)…", answers: ["La Autoridad de Registro (AR) firma digitalmente con su clave privada los certificados que genera.", "La Autoridad de Certificación (AC) da fe de que la asociación entre la clave pública y quien dice ser su propietario es correcta.", "La CRL (Certificate Revocation List) contiene la lista de certificados válidos y los que han dejado de serlo.", "Siempre se utiliza el programa PGP (Pretty Good Privacy), que es un sistema criptográfico híbrido."], correct: 1 },
    
    { question: "30. En criptografía, respecto a la función hash podemos afirmar que...", answers: ["Es un algoritmo de cifrado asimétrico basado en factorización de números, sabiendo que factorizar números productos de dos grandes primos no es posible.", "Sirve para obtener llaves o resúmenes de un determinado texto o mensaje, en donde por cada texto o mensaje se obtienen dos o más resúmenes.", "Si el resultado de aplicar una función hash a dos textos, es diferente, podemos deducir que también los textos lo son.", "Una función hash buena es aquella que experimenta el mayor número de colisiones posibles."], correct: 2 },
    
    { question: "31. En una comunicación confidencial entre dos usuarios \"A\" y \"B\", que utilizan un sistema criptográfico de clave asimétrica, si el usuario \"A\" envía al usuario \"B\" un mensaje, …", answers: ["Se cifra con la clave pública de \"A\", y \"B\" lo descifra con la clave privada de \"A\".", "Se cifra con la clave pública de \"B\", y \"B\" lo descifra con su clave privada.", "Se cifra y se descifra con una clave conocida por ambos.", "Se cifra con la clave privada de \"A\", y \"B\" lo descifra con la clave pública de \"A\"."], correct: 1 },
    
    { question: "32. Podemos definir SHA como:", answers: ["Un conjunto de funciones hash criptográficas.", "Un virus polimórfico.", "La extensión de los ficheros no legibles generados por \"Shell Scrap\".", "La extensión de los archivos ejecutables comprimidos."], correct: 0 },
    
    { question: "33. ¿Cuál de las siguientes afirmaciones es incorrecta?", answers: ["AES (Advanced Encryption Standard) es un protocolo de encriptación de clave simétrica.", "DES (Data Encryption Standard) es un algoritmo de cifrado que utiliza técnicas de clave asimétrica.", "SHA (Secure Hash Algorithm) es un sistema de funciones hash diseñado por la Agencia de Seguridad Nacional de EEUU.", "MD5 (Message Digest algorithm 5) es una función hash de 128 bits usada en criptografía."], correct: 1 },
    
    { question: "34. En relación con las funciones hash o funciones de resumen empleadas en la firma digital, indicar cuál de las siguientes afirmaciones es cierta.", answers: ["Dado un mensaje M, debe ser extremadamente difícil encontrar otro mensaje M', tal que ambos presenten el mismo resumen h(M)=h(M').", "Dado el resumen h(M) debe ser posible calcular M con una complejidad temporal lineal.", "Las respuestas A) y B) son las dos ciertas.", "Las respuestas A) y B) son las dos falsas."], correct: 0 },
    
    { question: "35. De acuerdo con la Ley 59/2003, de 19 de diciembre, de firma electrónica, señálese la falsa:", answers: ["La prestación de servicios de certificación no está sujeta a autorización previa y se realizará en régimen de libre competencia.", "Un certificado electrónico es un documento firmado electrónicamente por un prestador de servicios de certificación que vincula unos datos de verificación de firma a un firmante y confirma su identidad.", "El firmante es la persona que posee un dispositivo de creación de firma y que actúa en nombre propio o en nombre de una persona física o jurídica a la que representa.", "La custodia de los datos de creación de firma asociados a cada certificado electrónico de persona jurídica será responsabilidad del prestador de servicios de certificación, cuya identificación se incluirá en el certificado electrónico."], correct: 3 },
    
    { question: "36. De acuerdo con lo establecido en el Artículo 3 de la Ley 59/2003, de 19 de diciembre, de firma electrónica, señálese la falsa:", answers: ["La firma electrónica es el conjunto de datos en forma electrónica, consignados junto a otros o asociados con ellos, que pueden ser utilizados como medio de identificación del firmante.", "La firma electrónica avanzada es la firma electrónica que permite identificar al firmante y detectar cualquier cambio ulterior de los datos firmados, que está vinculada al firmante de manera única y a los datos a que se refiere y que ha sido creada por medios que el firmante puede mantener bajo su exclusivo control.", "La firma electrónica reconocida es la firma electrónica generada a través del documento nacional de identidad electrónico.", "La firma electrónica reconocida tendrá respecto de los datos consignados en forma electrónica el mismo valor que la firma manuscrita en relación con los consignados en papel."], correct: 2 },
    
    { question: "37. Indicar cual de las siguientes afirmaciones es cierta:", answers: ["En los algoritmos criptográficos simétricos, la simetría queda de manifiesto por el hecho de poder cifrar utilizando tanto la clave pública como la clave privada.", "La firma digital con función de resumen, siempre requiere cifrar todo el documento.", "La probabilidad de éxito en un ataque de fuerza bruta (brute force) en un tiempo dado, es inversamente proporcional a la longitud de la clave establecida por el criptosistema.", "Ninguna de las respuestas anteriores es cierta."], correct: 2 },
    
    { question: "38. Indicar cuál de los siguientes no es un algoritmo de encriptación simétrico:", answers: ["DES (Data Encryption Standard).", "BlowFish.", "Rijndael.", "MD5."], correct: 3 },
    
    { question: "39. De acuerdo con el estándar X.509 de la UIT-T, la estructura de un certificado digital contiene, entre otra, la siguiente información (señálese la falsa):", answers: ["La CA firmante.", "El tiempo de validez.", "La clave privada.", "Firma digital del certificado."], correct: 2 },
    
    { question: "40. Indicar cuál de las siguientes afirmaciones es cierta:", answers: ["Los algoritmos de cifrado simétricos son más seguros que los asimétricos ya que los usuarios implicados en la comunicación no tienen que intercambiar ningún tipo de clave.", "Para una misma longitud de clave y mensaje, los algoritmos simétricos necesitan mayor tiempo de proceso en las operaciones de cifrado y descifrado.", "El algoritmo Rivest, Shamir y Adleman (RSA) es un algoritmo asimétrico utilizado como función de resumen (hash).", "Ninguna de las respuestas anteriores es cierta."], correct: 3 },
	
	    { question: "41. ¿En qué zona del chip del DNI electrónico se encuentra el certificado x509 de componente?", answers: ["Zona de seguridad.", "Zona autónoma.", "Zona privada.", "Zona pública."], correct: 3 },
    
    { question: "42. La Ley 34/2002, de 11 de julio, de Servicios de la Sociedad de la Información y de Comercio Electrónico, en el artículo 45 detalla la prescripción para las sanciones e infracciones. Señale la respuesta correcta:", answers: ["Las infracciones muy graves prescribirán a los 3 años, las graves al año y las leves a los 6 meses.", "Las sanciones impuestas por faltas muy graves prescribirán a los 3 años, las impuestas por faltas graves a los 2 años y las impuestas por faltas leves a los seis meses.", "Las infracciones muy graves prescribirán a los 5 años, las graves a los 3 años y las leves al año.", "Las sanciones impuestas por faltas muy graves prescribirán a los 3 años, las impuestas por faltas graves a los 2 años y las impuestas por faltas leves al año."], correct: 3 },
    
    { question: "43. La prestación de los servicios de validación del DNI electrónico se realiza en base a:", answers: ["Online Certificate Status Protocol (OCSP).", "Online Services Protocol (OSP).", "Services Status Protocol (SSP).", "Online Status Services Certificate (OSSC)."], correct: 0 },
    
    { question: "44. En el ámbito de la criptografía asimétrica, ¿cuál de las siguientes afirmaciones es cierta?", answers: ["La clave pública sirve para firmar los documentos, antes de enviarlos.", "La clave privada sirve para cifrar la clave pública antes de firmar con esta última un documento.", "La clave privada se ha de generar aleatoriamente a partir de la clave pública cada vez que se firma un documento.", "La clave pública sirve para comprobar la firma digital de un documento firmado."], correct: 3 },
    
    { question: "45. Señale la respuesta correcta. En una comunicación HTTPS, ¿qué tipo de cifrado se utiliza?", answers: ["Simétrico exclusivamente.", "Asimétrico exclusivamente.", "No se utiliza ningún cifrado.", "Tanto el simétrico como el asimétrico."], correct: 3 },
    
    { question: "46. Si a un mensaje le aplicamos una función hash, ciframos el resultado con una clave privada y se lo enviamos a un tercero junto con el mensaje original conseguimos:", answers: ["Autenticación, Integridad y No repudio en origen.", "Confidencialidad, Integridad y No repudio en origen.", "Autenticación, Confidencialidad e Integridad.", "Autenticación, Confidencialidad y No repudio en origen."], correct: 0 },
    
    { question: "47. SHA-1 produce un valor hash de:", answers: ["20 bytes.", "33 bytes.", "256 y 512 bits, respectivamente.", "256 bits."], correct: 0 },
    
    { question: "48. ¿Cuál de las siguientes afirmaciones es correcta en relación con el estándar de cifrado DES?", answers: ["La clave para el cifrado y el descifrado de la información son la misma.", "La clave para el cifrado y el descifrado de la información son diferentes, pero del mismo tamaño (mismo número de bits).", "La clave para el cifrado y el descifrado de la información son diferentes y de diferente tamaño (distinto número de bits).", "DES utiliza claves asimétricas de 132 bits de tamaño."], correct: 0 },
    
    { question: "49. ¿Qué duración tiene el certificado incorporado en el DNIe?", answers: ["Tendrá un período de vigencia de 24 meses.", "Tendrá un período de vigencia de 30 meses.", "Tendrá un período de vigencia de 36 meses.", "Tendrá el mismo periodo de vigencia que el indicado en la tarjeta del Documento Nacional de Identidad."], correct: 1 },
    
    { question: "50. Según lo establecido en el artículo 8 de la Ley 59/2003, de 19 de diciembre, de firma electrónica, el período de validez de los certificados reconocidos:", answers: ["No podrá ser superior a cinco años.", "No podrá ser superior a cuatro años.", "No podrá ser superior a tres años.", "No podrá ser superior a diez años."], correct: 0 },
    
    { question: "51. La criptografía de clave pública", answers: ["utiliza dos claves públicas", "utiliza una clave pública para descifrar", "utiliza una clave pública para cifrar y otra privada para descifrar y firmar", "ninguna de las anteriores es correcta"], correct: 2 },
    
    { question: "52. El protocolo SSL:", answers: ["utiliza algoritmos de clave simétrica para el cifrado de los datos", "utiliza algoritmos de clave asimétrica para el cifrado de los datos", "utiliza el algoritmo DSAX para el cifrado de los datos", "ninguna de las anteriores es correcta"], correct: 0 },
    
    { question: "53. En un criptosistema de claves publicas y privadas para enviar un mensaje cifrado se precisa:", answers: ["disponer de la clave pública del destinatario.", "disponer de la clave privada del destinatario.", "disponer de la nuestra propia clave pública.", "disponer de nuestra propia clave privada."], correct: 0 },
    
    { question: "54. Con el empleo de una firma digital, se obtiene los siguientes servicios de seguridad:", answers: ["confidencialidad e integridad.", "confidencialidad y autentificación.", "integridad y autentificación.", "confidencialidad, integridad y autentificación."], correct: 2 },
    
    { question: "55. ¿Cuál de las siguientes afirmaciones es FALSA respecto a los Certificados Electrónicos?", answers: ["No se puede suspender por ninguna causa su vigencia.", "EI fallecimiento o extinción de la personalidad jurídica del firmante extingue su vigencia.", "EI periodo de validez de los certificados electrónicos será adecuado a las características y tecnología empleada para generar los datos de creación de la firma.", "Se puede extinguir su vigencia por resolución judicial o administrativa que lo ordene."], correct: 0 },
    
    { question: "56. Para la expedición de certificados electrónicos, la empresa certificadora, podrá recabar datos personales:", answers: ["Solo directamente de los firmantes, o previo consentimiento expreso de estos", "De cualquier base de datos Pública o Privada", "De cualquier base de datos Pública, informándolo con posterioridad al firmante", "De ninguna fuente"], correct: 0 },
    
    { question: "57. Definición de Firma electrónica reconocida:", answers: ["Es la Firma electrónica avanzada basada en un certificado reconocido y generada mediante un dispositivo seguro de creación de firma.", "Es la Firma electrónica avanzada basada en un certificado reconocido y generada mediante un dispositivo no seguro de creación de firma.", "Conjunto de datos en forma electrónica, consignados junto a otros o asociados con ellos, que pueden ser utilizados como medio de identificación del firmante.", "Conjunto de datos en forma electrónica, consignados junto a otros o asociados con ellos, que pueden ser utilizados como medio de identificación del firmante y que está vinculada al firmante de manera única ya los datos a que se refiere."], correct: 0 },
    
    { question: "58. ¿Cuál de los siguientes protocolos permite conocer en tiempo real si un certificado ha sido o no revocado?", answers: ["OCSP", "CRL", "PKCS#10", "HTTPS"], correct: 0 },
    
    { question: "59. ¿Cuál de los siguientes modos de funcionamiento NO se corresponde con el algoritmo de cifrado DES?", answers: ["Modo ECB (Electronic CodeBook).", "Modo CBC (Cipher Block Chaining).", "Modo OFB (Output FeedBack).", "Modo UBC (Uncipher Block Chaining)."], correct: 3 },
    
    { question: "60. Según se establece en la Ley 59/2003, de Firma Electrónica, la cuantía de las multas para los distintos tipos de infracciones serán:", answers: ["Para las muy graves de 300.001 a 600.000 euros; graves de 30.001 a 300.000 euros; leves hasta 60.000 euros.", "Para las muy graves de 150.001 a 600.000 euros; graves de 60.001 a 150.000 euros; leves hasta 60.000 euros.", "Para las muy graves de 150.001 a 300.000 euros; graves de 60.001 a 150.000 euros; leves hasta 30.000 euros.", "Para las muy graves de 150.001 a 600.000 euros; graves de 30.001 a 150.000 euros; leves hasta 30.000 euros."], correct: 3 },
    
    { question: "61. ¿Cuándo se utiliza el algoritmo Hash en el proceso de firma?", answers: ["Sólo cuando se firma el documento, para generar el resumen.", "Sólo cuando se verifica la firma, al desencriptar.", "Se usa en los dos procesos de la misma forma.", "Se utilizan dos Hash diferentes, uno para firmar, y otro inverso, para verificar la firma."], correct: 2 },
    
    { question: "62. Ana y Bernardo tienen sus respectivos pares de claves privada y pública. Teniendo en cuenta que las claves públicas están disponibles para todos los usuarios del sistema, indique qué afirmación NO es correcta.", answers: ["Si Ana cifra un mensaje con la clave pública de Bernardo, solo Bernardo podrá descifrarlo con su clave privada.", "Si Ana cifra un mensaje con su clave pública, cualquiera podrá descifrarlo.", "Si Ana cifra un mensaje con su clave privada, cualquiera podrá descifrarlo con la clave pública de Ana.", "Si Ana cifra un mensaje con su clave privada, no puede negar que creó y firmó dicho mensaje (no repudio)."], correct: 1 },
    
    { question: "63. Una Infraestructura de Clave Pública (PKI en inglés) es un conjunto de protocolos, servicios y estándares que soportan aplicaciones basadas en criptografía de clave pública. Señale qué servicio NO proporciona.", answers: ["Emisión de un certificado para una clave pública.", "Publicación de las claves públicas de los usuarios.", "Comprobación de la validez de un certificado y de las operaciones permitidas para dicho certificado.", "Protección de las claves privadas de los usuarios."], correct: 3 },
    
    { question: "64. Son algoritmos de cifrado simétrico:", answers: ["3DES, AES y RC5", "DES, IDEA y SHA-1", "Blowfish, MD5 y AES", "DES, IDEA y MD5"], correct: 0 },
    
    { question: "65. Según el artículo 10 de la Ley 34/2002 de servicios de la Sociedad de la Información y de comercio electrónico, expone qué información está obligado el prestador de servicios de la sociedad de la información a poner a disposición por medios electrónicos, señale la FALSA entre las siguientes:", answers: ["Los prestadores de servicios de intermediación que presten colaboración con la entidad.", "Los datos de su inscripción en el Registro Mercantil o el registro público en el que haya adquirido personalidad jurídica.", "El número de identificación fiscal que le corresponda.", "Su dirección de correo electrónico."], correct: 0 },
    
    { question: "66. Conforme a la Ley 25/2013, de 27 de diciembre, de impulso de la factura electrónica y creación del registro contable de facturas en el Sector Público, las facturas que se remitan a las Administraciones Públicas serán electrónicas y se ajustarán al siguiente formato:", answers: ["factura electrónica Facturae versión 3.2.x con firma electrónica SAdES.", "factura electrónica Facturae versión 3.2.x con firma electrónica XAdES.", "factura electrónica Facturae versión 3.2.x con firma electrónica CAdES.", "factura electrónica Facturae versión 3.2.x con firma electrónica PAdES."], correct: 1 }
];