const tema36 = [
       
    { question: "01. El contenido de la cookies que hemos enviado con setcookie() lo podemos comprobar en:", answers: ["$HTTP_COOKIE_VARS", "$_REQUEST", "$_COOKIE", "Todos los anteriores son posibles"], correct: 3 },
    
    { question: "02. Atendiendo al concepto de Portal en la Web, ¿qué afirmación es la correcta?", answers: ["Yahoo fue el primer portal conocido y surgió en 1974 cuando se empezaron a clasificar direcciones Web con el fin de facilitar su correcta ubicación.", "Es el lugar de la página Web destinado exclusivamente a alojar los títulos y cabeceras.", "Es un término utilizado para referirse a un sitio Web que sirve de punto de partida para iniciar la navegación en Internet.", "Entre los servicios que ofrece destacan el motor de búsqueda y el chat, pero no el correo electrónico."], correct: 2 },
    
    { question: "03. Si en el navegador Microsoft Edge, necesita usted buscar los certificados de usuario instalados para el perfil que se encuentre logado en el sistema, debería realizar la siguiente operación:", answers: ["Seleccionar el menú Configuración/Privacidad, búsqueda y servicios/Seguridad/Administrar Certificados.", "Seleccionar el menú Configuración/Seguridad/Administrar Certificados.", "Seleccionar el menú Configuración/Opciones de Internet/Certificados.", "Seleccionar el menú Configuración/Seguridad/Administrar Certificados."], correct: 0 },
    
    { question: "04. Si tenemos en cuenta la clasificación de los portales en función del público hacia el que van destinados, aquellos que se dirigen a usuarios interesados en temas específicos y/o especializados se denominan:", answers: ["Portales verticales.", "Portales circulares.", "Portales móviles o megaportales.", "Portales horizontales"], correct: 0 },
    
    { question: "05. En un Portal, el proceso de aprobación de elementos es una serie de uno o más pasos en una ruta de aprobación. Estos elementos pueden colocarse en serie o en paralelo. En un sistema de aprobación en paralelo, ¿es posible configurarlo de modo que sea suficiente la aprobación de uno de los pasos para la visualización del elemento? Indicar la respuesta correcta.", answers: ["No. Siempre deben aprobarlo todos los pasos.", "Sí, y se denomina Paralell Any", "Sí, y se denomina Paralell All", "No. No es posible la aprobación en paralelo."], correct: 1 },
    
    { question: "06. Si en Internet hacemos referencia a un gestor de contenidos, indica cuál de las siguientes respuestas ES INCORRECTA.", answers: ["Es una aplicación informática usada para crear, editar, gestionar y publicar contenido digital multimedia en diversos formatos.", "Impide el tratamiento independiente del contenido y del diseño en una página Web.", "Genera páginas dinámicas interactuando con el servidor para generar la página Web bajo petición del usuario, con el formato predefinido y el contenido extraído de la base de datos del servidor.", "Facilita el acceso a la publicación de contenidos a un mayor número de usuarios, dado que no requiere de conocimientos de programación."], correct: 1 }
];