const tema1902 = [
    { question: "17. El intervalo o la latencia de tiempo entre la última transacción de datos confirmada antes del error y los datos más recientes recuperados después del error se denomina:", answers: ["Objetivo de tiempo de recuperación (RTO).", "Objetivo de punto de recuperación (RPO).", "Objetivo de nivel de recuperación (RLO).", "Objetivo de datos de recuperación (RDO)."], correct: 1 },
    
    { question: "18. Respecto a la tecnología de almacenamiento InnoDB señale la respuesta afirmativa:", answers: ["InnoDB es una tecnología de almacenamiento de datos de código abierto para la base de datos Oracle.", "Es la tecnología de almacenamiento de datos por defecto por el sistema administrador de bases de datos relacionales MySQL.", "Se basa en el código ISAM.", "No permite las búsquedas denominadas full-text, que para conjuntos de datos grandes son mucho más eficientes."], correct: 3 },
    
    { question: "19. ¿Cuál de las siguientes herramientas utiliza un SGBD (sistema de gestión de bases de datos) para asegurar la atomicidad y persistencia de las transacciones?", answers: ["Módulo de comprobación de la integridad.", "El esquema conceptual.", "Fichero diario.", "Triggers."], correct: 2 },
    
    { question: "20. En una base de datos relacional en la que se tiene información guardada en una tabla de provincias y además se dispone de una tabla de municipios donde parte de la clave es la provincia, ¿se puede borrar un elemento de la tabla de provincias manteniendo la integridad del sistema?", answers: ["Si, una vez que los municipios ya existen no hay ningún problema.", "Si, aunque no podría dar de alta nuevos municipios de esa provincia.", "Sólo si no hay ninguna población perteneciente a esa provincia.", "No, la tabla de provincias no puede cambiar ya que son un elemento estable."], correct: 2 },
    
    { question: "21. ANSI/ISO SQL define ciertos niveles de aislamiento en transacciones en función de qué fenómenos puede que ocurran. Indique la respuesta correcta respecto al fenómeno \"lectura fantasma\":", answers: ["Se permite en read uncommitted, read committed y repeatable read, pero no se permite en serializable.", "Se permite en read uncommitted y read committed, pero no se permite en repeatable read ni en serializable.", "Se permite en read uncommitted y repeatable read, pero no se permite en read committed ni en serializable.", "Se permite en read uncommitted, pero no se permite en read committed, repeatable read ni en serializable."], correct: 0 },
    
    { question: "22. El término anglosajón \"ACID\" relacionado con una transacción de base de datos se corresponde con las propiedades:", answers: ["Autentication, Consistency, Integrity, Durability.", "Atomicity, Confidentiality, Identification, Durability.", "Atomicity, Consistency, Isolation, Durability.", "Availabi lity, Consistency, Isolation, Durability."], correct: 2 },
    
    { question: "23. En relación con la concurrencia en bases de datos, el tamaño del elemento de datos adecuado para el bloqueo (granularidad) afecta al grado de concurrencia de forma que, a menor tamaño del elemento que es bloqueado:", answers: ["Aumenta el grado de concurrencia, aumenta la carga de trabajo para la gestión de bloqueos y el espacio ocupado por la información de bloqueos.", "Disminuye el grado de concurrencia, aumenta la carga de trabajo para la gestión de bloqueos y el espacio ocupado por la información de bloqueos.", "Disminuye el grado de concurrencia, disminuyendo la carga de trabajo para la gestión de bloqueos y el espacio ocupado por la información de bloqueos.", "Aumenta el grado de concurrencia, disminuyendo la carga de trabajo para la gestión de bloqueos y el espacio ocupado por la información de bloqueos."], correct: 0 },
    
    { question: "24. La instrucción que aborta la transacción en un SGBD y la hace terminar en forma no exitosa se denomina:", answers: ["Undo.", "Rollback.", "Two Phase Commit.", "Commit."], correct: 1 },
    
    { question: "25. Al problema en un SGBD en que dos transacciones paralelas intentan modificar el mismo objeto de la base de datos, leyendo ambas el valor antes de que la otra transacción lo actualice, se conoce como:", answers: ["Lectura sucia.", "Lectura fantasma.", "Lectura no repetible.", "Lectura comprometida."], correct: 2 }
];

