const tsupcyl2024 = [
    
    { question: "09. ¿Qué es un sistema de control de versiones en el desarrollo de software?", answers: ["Un sistema que protege el código fuente contra cualquier modificación.", "Una herramienta para gestionar cambios sobre un producto software a lo largo del tiempo.", "Un sistema que impide la distribución de software.", "Un sistema que verifica la calidad del software."], correct: 1 },
    
    { question: "10. El mantenimiento actualizado del software y de los sistemas operativos con las últimas versiones, parches de seguridad y actualizaciones disponibles para asegurar el rendimiento óptimo y proteger el sistema contra vulnerabilidades, se define como mantenimiento:", answers: ["Correctivo.", "Adaptativo.", "Perfectivo.", "Preventivo."], correct: 3 },
    
    { question: "11. ¿Qué caracteriza al diseño web adaptativo (Responsive Web Design)?", answers: ["Se adapta automáticamente a las preferencias del usuario sin intervención del diseñador.", "Implica utilizar colores y fuentes llamativas para captar la atención del usuario.", "Está limitado a dispositivos específicos, como teléfonos inteligentes.", "Ajusta el contenido y la presentación de una página web según las características del dispositivo y el tamaño de la pantalla."], correct: 3 },
    
    { question: "12. ¿Cuál de las siguientes afirmaciones es verdadera con respecto a un gráfico GANTT?", answers: ["Muestra solo las tareas principales en un proyecto.", "No es útil para programar y dar seguimiento a las tareas en un proyecto.", "Permite visualizar las fechas de inicio y finalización de las tareas.", "No es adecuado para proyectos que involucran múltiples recursos."], correct: 2 },
    
    { question: "13. En el modelo PaaS indica cuál de las siguientes afirmaciones describe mejor sus características:", answers: ["PaaS ofrece una plataforma completa que incluye infraestructura, herramientas de desarrollo, middleware y servicios de aplicación.", "PaaS proporciona servicios de almacenamiento en la nube para usuarios finales.", "PaaS se enfoca exclusivamente en la virtualización de servidores y recursos de red.", "PaaS está limitado a la gestión de infraestructuras físicas locales en lugar de entornos en la nube."], correct: 0 },
    
    { question: "14. En el desarrollo de aplicaciones iOS, indica cuál de los siguientes patrones de diseño de software es un patrón de diseño de comportamiento utilizado para estructurar la interfaz de usuario y permitir que los objetos se comuniquen entre sí de manera eficiente:", answers: ["Singleton.", "Observer.", "Factory Method.", "Decorator."], correct: 1 },
    
    { question: "15. En comparación con las BBDD relacionales, MongoDB es la solución ideal para almacenar:", answers: ["Datos estructurados con potencial de un crecimiento rápido.", "Datos no estructurados con un crecimiento lento.", "Datos no estructurados con muchas relaciones entre sí.", "Datos estructurados y no estructurados con un potencial de crecimiento rápido."], correct: 3 },
    
    { question: "16. En Java, ¿cuál de las siguientes afirmaciones describe correctamente el uso de la palabra clave final en la declaración de variables?", answers: ["final se utiliza para indicar que la variable no puede ser modificada después de su inicialización.", "final se utiliza para declarar una constante que puede ser utilizada sin necesidad de ser inicializada al momento de la declaración.", "final se aplica tanto a variables primitivas como a objetos.", "final indica que la variable puede ser modificada, pero solo dentro del mismo paquete."], correct: 0 },
    
    { question: "17. En inteligencia artificial, indica cuál de las siguientes afirmaciones es correcta en la Búsqueda primero el mejor:", answers: ["La búsqueda primero el mejor es siempre completa y obtiene una solución con el mínimo número de operadores.", "La búsqueda primero el mejor no siempre es completa, pero siempre obtiene una solución con el mínimo número de operadores.", "La búsqueda primero el mejor siempre es completa, pero no necesariamente obtiene una solución con el mínimo número de operadores.", "La búsqueda primero el mejor no siempre es completa ni siempre obtiene una solución con el mínimo número de operadores."], correct: 3 },
    
    { question: "18. En MÉTRICA 3, indica cuál es una tarea del proceso Análisis del Sistema de Información:", answers: ["Aceptación de la arquitectura del sistema.", "Especificación de casos de uso, siendo opcional en el caso de análisis estructurado y obligatorio en el caso de orientación a objetos.", "Optimización del modelo físico de datos.", "Realización de las pruebas unitarias."], correct: 1 },
    
    { question: "19. En el uso habitual de un algoritmo criptográfico SHA2 destinado a detectar cualquier cambio no autorizado en la información contenida, ¿qué principio de seguridad informática estaremos aplicando?", answers: ["Trazabilidad.", "Confidencialidad.", "Disponibilidad.", "Integridad."], correct: 3 },
    
    { question: "20. Dentro del ámbito del Diseño Orientado a Objetos (DOO), ¿qué elementos definen a un objeto?", answers: ["Su cardinalidad y tipo.", "Sus atributos y métodos.", "La forma en que establece comunicación e intercambia mensajes.", "Su interfaz y los eventos asociados."], correct: 1 },
    
    { question: "21. Indica cuál de las siguientes es una herramienta para realizar pruebas de software:", answers: ["Cassandra.", "Nginx.", "Blockchain.", "Jmeter."], correct: 3 },
    
    { question: "22. Según el modelo definido por la Fundación Europea para la Gestión de la Calidad (EFQM), indica cuál NO es un concepto fundamental de la excelencia:", answers: ["La orientación hacia los resultados.", "El liderazgo y la coherencia en los objetivos.", "El desarrollo de alianzas.", "La planificación a corto plazo."], correct: 3 },
    
    { question: "23. En el ámbito de la disponibilidad de la información ¿qué es el RPO?", answers: ["Establece el punto anterior en el tiempo al que una empresa está dispuesta a volver para recuperar sus datos y funcionalidades en caso de un incidente o desastre, es decir, define cuánta pérdida de datos puede tolerar una organización.", "Establece el tiempo máximo que una empresa puede permitirse estar inactiva antes de que se restablezcan sus sistemas y servicios después de un incidente, es decir, se centra en la restauración de la funcionalidad y la continuidad operativa de la organización.", "Establece la cantidad máxima de tiempo tolerable que se necesita para verificar el sistema y/o la integridad de los datos después de que se haya iniciado el proceso de recuperación, es decir, se concentra en el período necesario para asegurarse de que estos sistemas y datos estén funcionando correctamente y sin errores.", "Es una métrica para definir la cantidad total de tiempo que un proceso de negocio puede interrumpirse sin causar consecuencias inaceptables para la organización, es decir, representa el límite máximo de tiempo durante el cual una empresa puede estar inactiva y aún mantener su funcionamiento sin sufrir daños graves."], correct: 0 },
    
    { question: "24. ¿Cuál es el propósito principal del patrón de diseño Singleton en el desarrollo de software?", answers: ["Facilitar la creación de instancias múltiples de una clase.", "Garantizar que una clase tenga solo una instancia y proporcionar un punto de acceso global a ella.", "Permitir la herencia múltiple en las clases.", "Mejorar la legibilidad del código fuente."], correct: 1 },
    
    { question: "26. ¿Cuál es uno de los enfoques más comunes para lograr diseño adaptativo en CSS?", answers: ["Utilizar solo unidades fijas para garantizar consistencia.", "Media queries, que permiten aplicar estilos diferentes según las características del dispositivo.", "Ignorar completamente las diferencias de dispositivos y pantallas.", "Utilizar únicamente imágenes de alta resolución."], correct: 1 },
    
    { question: "27. ¿Cuál es la diferencia clave entre una base de datos operativa y un almacén de datos (data warehouse)?", answers: ["Las bases de datos operativas son para transacciones diarias, mientras que los almacenes de datos almacenan datos optimizados para análisis.", "Las bases de datos operativas son solo para datos históricos, mientras que los almacenes de datos se centran en datos en tiempo real.", "Los almacenes de datos son más pequeños en tamaño en comparación con las bases de datos operativas.", "Las bases de datos operativas no requieren mantenimiento regular."], correct: 0 },
    
    { question: "28. Dentro de una página HTML aparece este fragmento. Indica qué respuesta es la correcta: <p> Si hay error en la transacción en el servidor le aparecerá un error </p> <script> alert('Hay un error al procesar el pago'); </script> <p> No ha habido un error </p>", answers: ["El mensaje 'Hay un error al procesar el pago' se va a mostrar siempre en el navegador.", "El mensaje 'Hay un error al procesar el pago' solo se mostrará en el navegador si hay un error en la transacción.", "Se mostrará el mensaje 'Hay un error al procesar el pago' solo si hay cookies que permitan la comunicación entre el servidor y el navegador.", "No se mostrará el mensaje 'Hay un error al procesar el pago' en ningún caso."], correct: 0 },
    
    { question: "29. ¿Cuál de las siguientes afirmaciones describe mejor el propósito principal de SVG en desarrollo web?", answers: ["SVG se utiliza exclusivamente para la manipulación de datos en la capa del servidor.", "SVG proporciona una forma de definir gráficos vectoriales escalables en formato XML.", "SVG usa el mismo formato de compresión que jpg para ser escalable.", "SVG es una técnica de encriptación para proteger la privacidad de los usuarios en línea."], correct: 1 },
    
    { question: "30. Indica cuál de los siguientes operadores NO puede ser construido a partir de otros operadores SQL:", answers: ["INTERSECT", "EXCEPT", "UNION", "MINUS"], correct: 2 },
    
    { question: "32. Indica la respuesta que NO es correcta:", answers: ["HTTPS es la versión segura del protocolo HTTP.", "Utiliza cifrado basado en SSL/TLS.", "El puerto estándar de HTTPS es el 443.", "Basta con que la dirección web empiece por HTTPS para que sea una página segura."], correct: 3 },
    
    { question: "33. Ventajas de la versión SNMPv3 sobre SNMPv2:", answers: ["SNMPv2 presentaba debilidades en la recuperación de grandes cantidades de información.", "Introduce mecanismos de autentificación, privacidad y control de accesos más sólidos.", "SNMPv3 introdujo nuevas operaciones: GetBulk, Inform, Report.", "No aporta ninguna ventaja."], correct: 1 },
    
    { question: "34. La Red SARA:", answers: ["Sólo interconecta las Administraciones Públicas Españolas.", "Sólo interconecta la Administración General del Estado.", "Sólo interconecta las Comunidades Autónomas entre sí.", "Interconecta las Administraciones Públicas Españolas e instituciones europeas."], correct: 3 },
    
    { question: "35. ¿Qué herramienta del CCN-Cert permite una gestión de ciberincidentes?", answers: ["LUCIA.", "CORINTO.", "CARMEN.", "PLATA."], correct: 0 },
    
    { question: "36. En una red inalámbrica el SSID (Service Set Identifier) podemos afirmar que:", answers: ["Es una secuencia de un máximo de 32 caracteres.", "No puede contener caracteres numéricos.", "No es sensible a mayúsculas y minúsculas.", "Es el nombre con el que se identifica a cada uno de los dispositivos que se conectan a dicha red."], correct: 0 },
    
    { question: "37. En el contexto de un WAF (Web Application Firewall), podemos afirmar que:", answers: ["Las soluciones WAF nunca realizan inspección de tráfico HTTP.", "Existen soluciones WAF basadas en la nube.", "Un WAF siempre se instala en la intranet, detrás de las aplicaciones web.", "El objetivo de un WAF es proteger el tráfico entre servidores."], correct: 1 },
    
    { question: "38. En un ataque Zero-day podemos afirmar que:", answers: ["Aprovecha una vulnerabilidad de un software antes de que se publiquen y apliquen los parches que la corrigen.", "Intercepta mensajes entre dos víctimas poniéndose el atacante en medio de la comunicación.", "Es el uso de la línea telefónica convencional y de la ingeniería social para engañar personas y obtener información delicada como puede ser información financiera o información útil para el robo de identidad.", "Aprovecha vulnerabilidades conocidas en el caso de que aún no se haya aplicado el parche existente."], correct: 0 },
    
    { question: "39. Dada la máscara de red 255.255.240.0, ¿a qué red pertenece la dirección IP 192.228.17.15?", answers: ["192.228.0.0", "192.228.8.0", "192.228.16.0", "192.228.17.0"], correct: 2 },
    
    { question: "40. ¿Cuáles son los puertos estándar TCP que usan los protocolos de correo IMAP/IMAPS (respectivamente)?", answers: ["25/465.", "110/995.", "143/993.", "121/963."], correct: 2 }
];
